server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Read model CQRS (OpenSearch) -> product-search
    location = /api/products/_search {
        proxy_pass http://product-search:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Write model & API lain (PostgreSQL) -> product-backend
    location /api/ {
        proxy_pass http://product-backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA static (SvelteKit adapter-static)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
